### ISSUE TITLE
Which BIOS version are you on?

### ISSUE THREAD

**Issue by LavenderMP** [rursache/Hackintosh-13900k-Z690-AORUS-ELITE-AX-DDR5-AMD-6900XT#2]
I'm currently on F22 but sometime I got randomly freeze when I don't use my computer

**Comment by rursache** [comment]
I'm on version F21 and works without issues. I see no reasons not to work on newer versions as well.

Either provide more details (incl. full specs) or check another OS; I highly doubt it its a hackintosh/macOS issue.
