### ISSUE TITLE
Does not boot ...

### ISSUE THREAD

**Issue by BigBenOnGit** [rursache/Hackintosh-13900k-Z690-AORUS-ELITE-AX-DDR5-AMD-6900XT#3]
Hello, I recreated the setup and when booting it gets stuck at the apple logo and the loading bar (about 1%)... Any idea?

**Comment by rursache** [comment]
Make sure to disable CSM support and secure boot in BIOS and of course, generate serial numbers as the uploaded EFI have placeholders. I'm running the exact EFI on the system I'm typing this comment. If you have the same hardware, there is no reason not to work

**Comment by BigBenOnGit** [comment]
Hello Rursache,

I´ve got following hardware- config and getting stuck on:

"AppleFileSystemDriver: using boot-uuid ..." -> what would be next ... ?

Gigabyte Aorus Z690 Elite AX )Rev 1.x DDR5 (BIOS F23a)
WD_BLACK™ SN850X, first (CPU PCI4) NVMe Port
Corsair Vengeance 64GB DDR5 RAM
Intel 13900K, AMD 6900XT

Do you have a hint, on what I could look onto ?

Beste regards,

Benjamin

**Comment by rursache** [comment]
Please post the full log on pastebin and provide a link here
