### ISSUE TITLE
My "NH-D15" cooling is poor..

### ISSUE THREAD

**Issue by corot2a** [rursache/Hackintosh-13900k-Z690-AORUS-ELITE-AX-DDR5-AMD-6900XT#4]
My "NH-D15" cooling is poor, can you tell me how to lower the voltage in the BIOS to reduce the heat of the 13900K CPU?

**Comment by rursache** [comment]
Please use google or reddit for these questions, this repo is about this specific Hackintosh build and not about how to over/under clock/volt CPUs.
